name: SHIFT AT WORK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the CORONGAN/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/CORONGAN -v ${{ github.workspace }}/_site:/srv/CORONGAN/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/corongan && corongan build --future"
